[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  targetPort = 3000
  framework = "next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
